# Generated by Django 4.2.20 on 2025-05-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=14)),
                ("cidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("telefone", models.CharField(max_length=14)),
                ("cidade", models.CharField(max_length=100)),
                ("tipo", models.CharField(help_text="Por exemplo: ", max_length=100)),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="descrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("pode_editar", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Historia_Inspiradoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("conteudo", models.TextField()),
                ("data_postagem", models.DateTimeField(auto_now_add=True)),
                ("autor", models.CharField(max_length=100)),
                (
                    "doador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.doador",
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.instituicao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("1", "Dinheiro"), ("2", "Roupa"), ("3", "Alimento")],
                        max_length=100,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateTimeField()),
                (
                    "doador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.doador",
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.instituicao",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.status",
                    ),
                ),
            ],
        ),
    ]
